version: '3.3'

services:
  fastapi:
    build: .
    container_name: fastapi-genai
    ports:
      - "80:80"
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/fastapi
    depends_on:
      - postgres

  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"

  opensearch:
    image: opensearchproject/opensearch:1.3.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastapi
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  mlflow:
    build: .
    container_name: mlflow
    environment:
      - SERVICE=mlflow
    ports:
      - "5000:5000"
    volumes:
      - mlflow-data:/mlflow

volumes:
  opensearch-data:
  postgres-data:
  mlflow-data:
